### PR TITLE
Added Cellular and Voronoi Noise

### PR DESCRIPTION
**Pull request by DGruenwald**
I had to research this type of noise for a project of mine and thought what better way to experiment and learn how it works than implementing it here.

Cellular noise is based on randomly distributed points and the relationship between each xy-coordinate and the nearest of these points.

Here are some examples:

First, positive and negative cell noise.
Positive Cell Noise Negative Cell Noise

Voronoi noise, left "unweighted", making hard edges, right "weighted" causing rounded lines.
Voronoi unweighted Voronoi weighted

It has an especially nice effect if generated for each color channel.
RGB Voronoi RGB Negative Cell Noise
That last one is my favorite.

### CODE REVIEW

**Comment by schalkt** [comment]
Nice work. It is possible to create seamless textures?
May I use your source code in my own seamles javascript texture generator?
https://github.com/schalkt/tgen and http://seamless-texture.com/generator

**Comment by DGruenwald** [comment]
@schalkt Hmm... That's actually a really interesting question, and it turns out that it's pretty easy too.

Theoretically it should be possible by making the grid of random points simply wrap around on each edge.

However, there will be a problem when the grid size doesn't evenly divide the texture and the only solution I can think of is only allowing the grid to be of sizes that do.

**Comment by DGruenwald** [comment]
I've now also added fractal variants of the new noise types:
Positive Cellular Fractal Negative Cellular Fractal Voronoi Fractal

**Comment by mrdoob** [comment]
Nice! Many thanks! 😀

**Pull request merged**
